Bugfix/sfc var names update to make test pass (#1227)
## Description

```
mpasjedi_3dvar........................................................................failed
mpasjedi_3dvar_2pe....................................................................failed


Exception stack: 
UserError: airTemperature is specified as a simulated variable but it has not been specified as an observed or a derived variable.
```

To fix this failure updating the yaml to use new file with both
variables airTemperature and airTemperatureAt2M

## Issue(s) addressed

Resolves https://github.com/JCSDA-internal/ufo/issues/4181

## Dependencies
build-group=https://github.com/JCSDA-internal/ufo-data/pull/590
build-group=https://github.com/JCSDA-internal/ufo/pull/4251
List the other PRs that this PR is dependent on:
- [ ] https://github.com/JCSDA-internal/ufo-data/pull/590
- [ ] https://github.com/JCSDA-internal/ufo/pull/4251

## Impact

Expected impact on downstream repositories:

## Manual Testing Instructions (optional)

If you would like your reviewers to manually build and test the change,
please include
instructions on how the change should be built and tested. Also include
a short
justification on why manual testing is necessary for this change.

## Checklist

- [X] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [X] I have run the unit tests before creating the PR

---------

Co-authored-by: BenjaminRuston <benr@ucar.edu>