Fix physical limits for hydrometeors and latitude (#254)
TYPE: bug fix

KEYWORDS: hydrometeors, latitude, precision

DESCRIPTION OF CHANGES: 

Both of these bugs were found at 2018041818 w/ the 30km domain.

1. CRTM requires hydrometeor values >= 0.0.  There was some difference between the zero values in the IC restart file (probably single precision) and the hard limit of ZERO in CRTM.  This PR ensures that all hydrometeor values coming from getValues are >= 0.0 to double precision.

2. Recent changes in another repository causes a latitude value from mpas-jedi to trigger an exception.  The 30km restart file contains the following two latitude values: 1.57079637050629, -1.57079637050629.  These are larger in magnitude than PI/2 = 1.57079632679, causing the following exceptions in getvalues:
```
Exception: BadValue: Invalid latitude 90.000002504478161  (/glade/u/home/miesch/jedi/jedi-stack/pkg/eckit/src/eckit/geometry/Sphere.cc +187 convertSphericalToCartesian)
Exception: BadValue: Invalid latitude -90.000002504478161  (/glade/u/home/miesch/jedi/jedi-stack/pkg/eckit/src/eckit/geometry/Sphere.cc +187 convertSphericalToCartesian)
```

I do not know what piece of code calls these functions.  The only recent change I noticed that uses this code is in the Track Check of UFO (https://github.com/JCSDA/ufo/pull/802), but I'm not using that filter.  Either way, the offending latitude values at the poles need to be corrected.

ISSUE: none

LIST OF MODIFIED FILES: 
M       model/mpas2ufo_vars_mod.F90
M       model/mpas_constants_mod.F90
M       model/mpas_geom_mod.F90

TESTS CONDUCTED: The offending case was tested and is fixed.  Ctests pass on Cheyenne.